Set nbits=0 (no classes) as default

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,9 +24,9 @@ ac_help="$ac_help
 ac_help="$ac_help
   --with-debug            compile with debug info"
 ac_help="$ac_help
-  --with-nbits=NBITS      set number of bits for class of addr (2)"
+  --with-nbits=NBITS      set number of bits for class of addr (0)"
 ac_help="$ac_help
-  --with-maxprefix=LEN    set maximum prefix length (24)"
+  --with-maxprefix=LEN    set maximum prefix length, 16..32 (24)"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -1797,7 +1797,7 @@ else
 fi
 
 
-nbits=2
+nbits=0
 maxprefix=24
 # Check whether --with-nbits or --without-nbits was given.
 if test "${with_nbits+set}" = set; then
@@ -1811,13 +1811,13 @@ if test "${with_minprefix+set}" = set; then
   maxprefix=$withval
 fi
 
-if echo $nbits | grep -q '[^0-9]' || [ $nbits -ne 1 -a $nbits -ne 2 -a $nbits -ne 4 -a $nbits -ne 8 -a $nbits -ne 16 ]
+if echo $nbits | grep -q '[^0-9]' || [ $nbits -ne 0 -a $nbits -ne 1 -a $nbits -ne 2 -a $nbits -ne 4 -a $nbits -ne 8 -a $nbits -ne 16 ]
 then
 	{ echo "configure: error: Incorrect nbits value $nbits" 1>&2; exit 1; }
 fi
 if echo $maxprefix | grep -q '[^0-9]' || [ $maxprefix -gt 32 -o $maxprefix -lt 16 ]
 then
-	{ echo "configure: error: Incorrect nbits value $nbits" 1>&2; exit 1; }
+	{ echo "configure: error: Incorrect maxprefix value $maxprefix" 1>&2; exit 1; }
 fi
 
 cat >> confdefs.h <<EOF
