*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -968,7 +968,7 @@ esac
 
 
 
-for ac_func in inet_aton
+for ac_func in inet_addr
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
 echo "configure:975: checking for $ac_func" >&5
@@ -1023,10 +1023,10 @@ else
 fi
 done
 
-case x$ac_cv_func_inet_aton in
+case x$ac_cv_func_inet_addr in
   xno)
-    echo $ac_n "checking for inet_aton in -lxnet""... $ac_c" 1>&6
-echo "configure:1030: checking for inet_aton in -lxnet" >&5
+    echo $ac_n "checking for inet_addr in -lxnet""... $ac_c" 1>&6
+echo "configure:1030: checking for inet_addr in -lxnet" >&5
     OLD_LIBS=$LIBS
     LIBS="$LIBS -lxnet"
     cat > conftest.$ac_ext <<EOF
@@ -1034,7 +1034,7 @@ echo "configure:1030: checking for inet_aton in -lxnet" >&5
 #include "confdefs.h"
 #include <arpa/inet.h>
 int main() {
-inet_aton("");
+inet_addr("");
 ; return 0; }
 EOF
 if { (eval echo configure:1041: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
@@ -1044,7 +1044,7 @@ else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -rf conftest*
-  echo "$ac_t""no" 1>&6 { echo "configure: error: no aton() found" 1>&2; exit 1; }
+  echo "$ac_t""no" 1>&6; { echo "configure: error: no inet_addr() found" 1>&2; exit 1; }
 fi
 rm -f conftest*
     ;;
