*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1044,7 +1044,7 @@ else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -rf conftest*
-  echo "$ac_t""no" 1>&6; { echo "configure: error: no aton() found" 1>&2; exit 1; }
+  echo "$ac_t""no" 1>&6 { echo "configure: error: no aton() found" 1>&2; exit 1; }
 fi
 rm -f conftest*
     ;;
