*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -968,15 +968,16 @@ esac
 
 
 
+
 for ac_func in inet_addr
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:975: checking for $ac_func" >&5
+echo "configure:976: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 980 "configure"
+#line 981 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -999,7 +1000,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1003: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1004: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -1026,18 +1027,18 @@ done
 case x$ac_cv_func_inet_addr in
   xno)
     echo $ac_n "checking for inet_addr in -lxnet""... $ac_c" 1>&6
-echo "configure:1030: checking for inet_addr in -lxnet" >&5
+echo "configure:1031: checking for inet_addr in -lxnet" >&5
     OLD_LIBS=$LIBS
     LIBS="$LIBS -lxnet"
     cat > conftest.$ac_ext <<EOF
-#line 1034 "configure"
+#line 1035 "configure"
 #include "confdefs.h"
 #include <arpa/inet.h>
 int main() {
 inet_addr("");
 ; return 0; }
 EOF
-if { (eval echo configure:1041: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1042: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   echo "$ac_t""yes" 1>&6
 else
@@ -1049,6 +1050,29 @@ fi
 rm -f conftest*
     ;;
 esac
+
+OLD_LIBS=$LIBS
+LIBS="$LIBS -lpcap"
+echo $ac_n "checking for libpcap""... $ac_c" 1>&6
+echo "configure:1058: checking for libpcap" >&5
+cat > conftest.$ac_ext <<EOF
+#line 1060 "configure"
+#include "confdefs.h"
+
+int main() {
+pcap_open_live();
+; return 0; }
+EOF
+if { (eval echo configure:1067: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  echo "$ac_t""yes" 1>&6
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  echo "$ac_t""no" 1>&6; { echo "configure: error: no libpcap found" 1>&2; exit 1; }
+fi
+rm -f conftest*
 
 # Check whether --with-vlans or --without-vlans was given.
 if test "${with_vlans+set}" = set; then
